name: 'octocov'

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  coverage:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      -
        name: Run tests
        run: npm run test:coverage
      -
        uses: k1LoW/octocov-action@v0
