name: 'script'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  coverage:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Display node/npm versions
        run: |
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        id: coverage-report
        run: |
          change_files="$(git diff --name-only --diff-filter=AM origin/${{ github.base_ref }}...HEAD | grep -E "src/.*\.(js|cjs|mjs|jsx|ts|tsx)$")";
          for i in "${!change_files[@]}"; do
            change_files[$i]=${change_files[$i]//src\//}
          done
          IFS="|";files="${change_files[*]}";unset IFS;
          npm run unit -- --coverage --collectCoverageFrom=$files --coverageReporters=json-summary
