name: 'coverage'
on:
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:coverage
          annotations: none
          custom-title: Coverage report for frontend
