name: 'coverage'
on:
  pull_request:
    branches:
      - master
    paths:
      - "app-frontend/assets/.node-version"
      - "app-frontend/assets/src/**/*.ts"
      - "app-frontend/assets/src/**/*.tsx"
      - "app-frontend/assets/package.json"
      - "app-frontend/assets/package-lock.json"
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  coverage:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
