name: 'coverage'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  coverage:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:coverage
          annotations: none
          custom-title: Coverage report for frontend

      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          test-script: npm run test:coverage
          annotations: none
          custom-title: Coverage report for frontend ver.2
          skip-step: install
          output: report-markdown
      
      - name: Set report as env variable
        run: printf 'REPORT="%s"\n' "${{ steps.coverage.outputs.report }}" >> $GITHUB_ENV

      - name: Display report
        run: printf "%s\n" "$REPORT"

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          # pass output from the previous step by id.
          message: ${{ env.REPORT }}
