name: 'coverage'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  coverage:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare files
        id: step1
        run: |
          change_files=($(git diff --name-only origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF} | grep -E 'src/.*\.(js|cjs|mjs|jsx|ts|tsx)$'))
          IFS="|";files="${change_files[*]}";unset IFS;
          echo "::set-output name=files::$files"
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npx jest --coverage --collectCoverageFrom=steps.step1.outputs.files
          annotations: none
          custom-title: Coverage report for frontend

          